### ISSUE TITLE
Would you recommend this over symfony/session?

### ISSUE THREAD

**Issue by notflip** [odan/session#11]
Hi Odan, Thank you for this package, I'm looking into your slim-4-skeleton and see that the symfony session is used there, which one would you recommend? Thank you for your work in the slim community.

**Comment by odan** [comment]
Hi @notflip This session library was created with PSR-7 and PSR-15 (Middleware) in mind. The focus is on sessions only, while the `symfony/http-foundation` component is not PSR-7 and PSR-15 based and also brings a lot of additional classes on board but also more session storage options, a stable API and very good support from the community. If you want to use a more widely used component and if you need more [storage adapters](https://symfony.com/doc/current/components/http_foundation/session_configuration.html#save-handlers), like the `PdoSessionHandler` or the `RedisSessionHandler` then better use the Symfony session component.
