### ISSUE TITLE
Documentation Correction

### ISSUE THREAD

**Issue by curVV** [odan/session#19]
Hi, not sure where to report minor issue on your blog.

On your blog page https://odan.github.io/2021/01/15/slim4-session.html, the last line of `src/Action/Auth/LoginSubmitAction.php`:

`$response->withStatus(302)->withHeader('Location', $url);`

...should be:

`return $response->withStatus(302)->withHeader('Location', $url);`

**Comment by odan** [comment]
Yes, the return statement was missing. It has been fixed now. Thanks for reporting.
