### ISSUE TITLE
Check session before start?

### ISSUE THREAD

**Issue by diwms** [odan/session#2]
Hi,
I would like to contribute to this package.
I use this package in pair with `slim/framework` and `slim/flash` packages.

In my case the problem in `SessionMiddleware` - i got notice from php that session is already started. It's because registering in dependency injection container `slim/flash` package assume that session is started and ready to work.

So, my idea is - improve a little bit `SessionMiddleware` by wrapping session start

```diff
- $this->session->start();
+ if ($session->isStarted() === false) { 
        $session->start();
}
```

What do you think? In case of approve I'll open PR with changes.

**Comment by odan** [comment]
I think that makes sense and would be a good improvement. Please create a PR.
