### ISSUE TITLE
Closing session

### ISSUE THREAD

**Issue by darkalchemy** [odan/session#21]
Hi @odan,

In SessionMiddleware.php you are closing the session almost immediately after opening the session. Is this the correct behavior? I ask because if I  comment out the line `$this->session->save()` my session works correctly,  but otherwise it fails. 

Of course, I could be using it incorrectly. I have tried adding this line `$app->addMiddleware($container->get(SessionMiddleware::class))` both as the first and the last middleware.

Could you please take a look and tell me if this is an error of my usage or in the middleware?

Thanks

**Comment by odan** [comment]
This behavior is expected, because it acts as an ingoing and outgoing middleware.
Please note that the middleware invokes the next middlewares by calling the handle method.
The session is not closed immediately, but only when the action handler is done and the middleware goes outside.

**Comment by darkalchemy** [comment]
Thanks @odan. I guess I still don't understand how middleware works, exactly.

Back to the books. :)
