### ISSUE TITLE
Version 6 - Roadmap

### ISSUE THREAD

**Issue by odan** [odan/session#28]
Here are some initial ideas:

* Provide interface for each concern.
  * Add `SessionManagerInterface` to handle session operations, such as `start`, `save`, `destroy`, `getName`, etc.
  * Reduce `SessionInterface` to handle session data operations only, e.g. `get`, `set`
* Make session settings "immutable"
* Remove `SessionAwareInterface` in favor of dependency injection
* Require PHP 8.0+

**Example usage**

```php
$config = [
    'name' => 'app',
];

$session = new Odan\Session\PhpSession($config);

$session->start();

$session->set('key', 'test123')

// test123
$value = $session->get('key');

$flash = $session->getFlash();
$flash->add('error', 'Invalid username or password');

// This is now optional
$session->save();
```

**Comment by sid606** [comment]
when I try this example from above it give me this error 
 Odan\Session\PhpSession::__construct(): Argument #1 ($storage) must be of type ?ArrayObject, array given, called in any solution
I have "odan/session": "^5.1"

OK I have to set to 6.x-dev to work

**Comment by odan** [comment]
Version 6 is not yet released. But you can already test it. It will be released in a few days.

**Comment by odan** [comment]
Version 6 has just been released.
