### ISSUE TITLE
Method "has"

### ISSUE THREAD

**Issue by kaxias** [odan/session#29]
why has the method "has" been removed?

**Comment by odan** [comment]
Hi! I tried to simplify the new SessionInterface to a minimum and I guess the `has` method was removed because the `get` method can also be used for such a use case. 

**Example**

```php
if ($session->get('key') === null) {
   // ...
}
```

If this doesn't make sense to you, I would offer a fix that adds the `has` method back again.

**Comment by odan** [comment]
Update: The `has` method has been added again according to the documentation.
