### ISSUE TITLE
session->has()

### ISSUE THREAD

**Issue by Fakes77** [odan/session#30]
Hi, in the v6 documentation it is possible to use ($session->has('foo')) but I didn't find anywhere in SessionInterface, it's only in FlashInterface is it possible to return it?

**Comment by odan** [comment]
Hi! The `has` method will be added again to the interface in the next days.

**Comment by odan** [comment]
Update: The `has` method has been added again according to the documentation.

Please update to v.6.1

**Comment by Fakes77** [comment]
Nice, thanks :)

ne 22. 1. 2023 v 12:04 odesílatel Daniel Opitz ***@***.***>
napsal:
