### ISSUE TITLE
SessionInterface.php

### ISSUE THREAD

**Issue by mat-k-witts** [odan/session#33]
AFAICT this interface does not implement:

1. start()
2. destroy()
3. regenerateId()

**Comment by odan** [comment]
There are different interfaces: SessionInterface and SessionManagerInterface.

Can you add more details please?

**Comment by mat-k-witts** [comment]
Slim4 Ebook:

```
use Odan\Session\SessionInterface;

[...]

public function __invoke(
ServerRequestInterface $request,
ResponseInterface $response
): ResponseInterface {

[...]

if ($user) {
// Login successfully
// Clears all session data and regenerate session ID
$this->session->destroy();
$this->session->start();
$this->session->regenerateId();

[...]
```

**Comment by odan** [comment]
This eBook article has already been updated to the latest version of this Session package.
You can download the latest eBook version (or read it online) via the link in your order confirmation.
If you have any further question, please send me an email.

Please note: There is also a public documentation for v6 available [here](https://odan.github.io/session/v6/).
