### ISSUE TITLE
PSR HTTP Message dependency

### ISSUE THREAD

**Issue by exeo-abid** [odan/session#36]
Hello Daniel,

I am trying to install this package as follows:

`composer require odan/session:^6.0`

I got the following error message:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires odan/session ^6.0 -> satisfiable by odan/session[6.0.0, 6.1.0].
    - odan/session[6.0.0, ..., 6.1.0] require psr/http-message ^1 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

When I installed using the `--with-all-dependencies` option, I see this happening:

```
Downgrading psr/http-message (2.0 => 1.1): Extracting archive
```

I am not familiar with the PSR HTTP Message 2.0 standard and what differences it imposes.  But I am wondering whether there is any impact to my application overall by downgrading.  From what I can tell, my applications dependency on the Google API library upgraded the http-message to 2.0 but it seems functional with 1.1 as well.

Thanks in advance for your feedback.

**Comment by odan** [comment]
Hi! Thanks for reporting. This should be fixed now in the latest version 6.2.0.
