### ISSUE TITLE
PSR-15 support

### ISSUE THREAD

**Issue by roxblnfk** [odan/session#5]
This repository have the "PSR-15" tag but, the [SessionMiddleware](https://github.com/odan/session/blob/master/src/SessionMiddleware.php) class does not implement the [MiddlewareInterface](https://github.com/php-fig/http-server-middleware/blob/master/src/MiddlewareInterface.php) interface from the [PSR-15](https://www.php-fig.org/psr/psr-15/)

**Comment by odan** [comment]
That's true. I think I added this tag, because it's planned add a PSR-15 middleware.

**Comment by odan** [comment]
The next major version will support the PSR-15 middeware as new default middleware.
