### ISSUE TITLE
How to set cookie and csrf

### ISSUE THREAD

**Issue by terabytesoftw** [odan/session#6]
I am interested in working with slim4, I have put the session middleware to work, how can I correctly implement cookies and csrf,

Thks,

**Comment by odan** [comment]
Hi @terabytesoftw 

> how can I correctly implement cookies and csrf,

Cookies are handled by this session library. You can use these methods to manage cookies:

```php
// Set session runtime configuration
// All supported keys: http://php.net/manual/en/session.configuration.php
$session->setOptions($options);

// Get session runtime configuration
$session->getOptions();

// Set cookie parameters
$session->setCookieParams(4200, '/', '', false, false);

// Get cookie parameters
$session->getCookieParams();
```

CSRF is not part of this library. But you could take a look at this here:

* https://github.com/odan/csrf
* https://github.com/slimphp/Slim-Csrf

Here is an example how to integrate `odan/session` and `odan/csrf` in combination with `league/container`:

* https://github.com/odan/psr7-skeleton/blob/master/config/container.php#L77:L87
* https://github.com/odan/psr7-skeleton/blob/master/config/container.php#L258

And here you can find an older Slim 3 example:

* https://github.com/odan/prisma/blob/master/config/container.php#L169:L181
* https://github.com/odan/prisma/blob/master/config/container.php#L123

I hope it helps you.

**Comment by terabytesoftw** [comment]
I am working with Yii3 and Slim4, the middleware works correctly, but the session does not generate the cookie.

```
SessionInterface::class => function (\Psr\Container\ContainerInterface $container) {
    $settings  = [
        'name' => 'webapp',
        'cache_expire' => 0,
        'cookie_httponly' => true,
        'cookie_secure' => true,
        'cache_limiter' => '',
        // garbage collection
        'gc_probability' => 1,
        'gc_divisor' => 1,
        'gc_maxlifetime' => 30 * 24 * 60 * 60,
    ];
    $session = new \Odan\Session\PhpSession();
    $session->setOptions($settings);
    return $session;
},

SessionMiddleware::class => function (\Psr\Container\ContainerInterface $container) {
    return new SessionMiddleware($container->get(SessionInterface::class));
},

CsrfMiddleware::class => function (ContainerInterface $container) {
    $session = $container->get(\Odan\Session\SessionInterface::class);
  
    // The CSRF middleware requires a valid session id
    if (!$session->isStarted()) {
        $session->start();
    }
    return new CsrfMiddleware(new Psr17Factory(), $session->getId());
},
```

Thks,

**Comment by terabytesoftw** [comment]
Solved,

Thks,
